name: x448_dart
description: X448 (RFC 7748) Elliptic-Curve Diffie–Hellman for Dart/Flutter with FlutterFlow-friendly base64 helpers.
version: 0.1.1
repository: https://github.com/Dom-Cogan/x448_dart
issue_tracker: https://github.com/Dom-Cogan/x448_dart/issues
homepage: https://pub.dev/packages/x448_dart

environment:
  sdk: ">=3.4.0 <4.0.0"

platforms:
  android:
  ios:
  macos:
  windows:
  linux:
  web:

dependencies:
  meta: ^1.11.0
  crypto: ^3.0.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
