tee .github/workflows/build-ios.yml >/dev/null <<'EOF'
name: Build iOS x448 static lib

on:
  workflow_dispatch:

jobs:
  ios:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Build libx448dart.a (arm64)
        run: |
          set -e
          SDK=$(xcrun --sdk iphoneos --show-sdk-path)
          mkdir -p build-ios
          # Build static x448 from submodule
          cmake -S third_party/x448 -B build-ios/x448 \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_SYSTEM_NAME=iOS \
            -DCMAKE_OSX_ARCHITECTURES=arm64 \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=11.0 \
            -DCMAKE_OSX_SYSROOT="$SDK" \
            -DBUILD_SHARED_LIBS=OFF
          cmake --build build-ios/x448 --config Release -j
          # Build wrapper and merge
          clang -c -arch arm64 -isysroot "$SDK" -miphoneos-version-min=11.0 \
            -Ithird_party/x448/include native/mobile_wrapper.c -o build-ios/wrapper.o
          libtool -static -o build-ios/libx448dart.a build-ios/x448/libx448.a build-ios/wrapper.o

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: libx448dart-a-ios
          path: build-ios/libx448dart.a
